<?php
/**
 * PartialRefundTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoReceiptsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MehrIt\OttoReceiptsApiClient;

/**
 * PartialRefundTest Class Doc Comment
 *
 * @category    Class
 * @description Provides details about a previous partial refund of an individual position item within refund receipts.
 * @package     MehrIt\OttoReceiptsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartialRefundTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PartialRefund"
     */
    public function testPartialRefund()
    {
    }

    /**
     * Test attribute "receipt_number"
     */
    public function testPropertyReceiptNumber()
    {
    }

    /**
     * Test attribute "position_item_id"
     */
    public function testPropertyPositionItemId()
    {
    }

    /**
     * Test attribute "receipt_creation_date"
     */
    public function testPropertyReceiptCreationDate()
    {
    }

    /**
     * Test attribute "partial_refund_amount"
     */
    public function testPropertyPartialRefundAmount()
    {
    }
}
