<?php
/**
 * ShippingCostTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoReceiptsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MehrIt\OttoReceiptsApiClient;

/**
 * ShippingCostTest Class Doc Comment
 *
 * @category    Class
 * @description Shipping costs, that are charged or reimbursed as part of this receipt.
 * @package     MehrIt\OttoReceiptsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingCostTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingCost"
     */
    public function testShippingCost()
    {
    }

    /**
     * Test attribute "delivery_fee_standard"
     */
    public function testPropertyDeliveryFeeStandard()
    {
    }

    /**
     * Test attribute "delivery_fee_freight_surcharge"
     */
    public function testPropertyDeliveryFeeFreightSurcharge()
    {
    }
}
