<?php
/**
 * TotalTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoReceiptsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MehrIt\OttoReceiptsApiClient;

/**
 * TotalTest Class Doc Comment
 *
 * @category    Class
 * @description Total amounts, which are charged or reimbursed of this receipt. Values are always positive. Whether it is an amount to be paid or refunded must be determined in context of the type of a receipt.
 * @package     MehrIt\OttoReceiptsApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TotalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Total"
     */
    public function testTotal()
    {
    }

    /**
     * Test attribute "gross"
     */
    public function testPropertyGross()
    {
    }

    /**
     * Test attribute "net"
     */
    public function testPropertyNet()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "amount_due"
     */
    public function testPropertyAmountDue()
    {
    }
}
