<?php
/**
 * ReceiptsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoReceiptsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MehrIt\OttoReceiptsApiClient;

use MehrIt\OttoReceiptsApiClient\Configuration;
use MehrIt\OttoReceiptsApiClient\ApiException;
use MehrIt\OttoReceiptsApiClient\ObjectSerializer;

/**
 * ReceiptsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MehrIt\OttoReceiptsApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReceiptsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getReceiptPdfUsingGET3
     *
     * Get the PDF document of a specific receipt by receipt number..
     *
     */
    public function testGetReceiptPdfUsingGET3()
    {
    }

    /**
     * Test case for getReceiptUsingGET5
     *
     * Get a specific receipt for the given receipt number as JSON object.
     *
     */
    public function testGetReceiptUsingGET5()
    {
    }

    /**
     * Test case for getReceiptsUsingGET5
     *
     * Get all receipts as list of JSON objects.
     *
     */
    public function testGetReceiptsUsingGET5()
    {
    }
}
